name: New Issue Opened Hook
on:
  issues:
    types: [opened]
jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up NodeJS 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: Run main script
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ISSUE_DATA: "#${{ github.event.issue.number }} [${{ github.event.issue.title }}](${{ github.event.issue.html_url }})"
        run: npm start || exit 0
