name: Delete opened issues not from "vtcaregorodtcev"
on:
  issues:
    types: [opened]
jobs:
  delete-issue:
    if: github.event.issue.user.login != 'vtcaregorodtcev'
    runs-on: ubuntu-latest
    steps:
      - uses: vtcaregorodtcev/delete-issue@main
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          issue_node_id: ${{ github.event.issue.node_id }}
